### ISSUE TITLE
Maintenance

### ISSUE THREAD

**Issue by danim47c** [platypusrex/next-type-graphql#1]
Hi, I'd be very good if you could maintain this project and show how did you used type-graphql with next.js.

Thanks

**Comment by platypusrex** [comment]
Hi @danim47c. I actually started this project around the same time my first child was born, and between that and work I just haven't made my way back to this one quite yet. It stills needs a little work, but I'll do my best to get this in proper shape for others to use and/or reference. I do have a slightly more advanced example that's using typeorm as well. I'll see if I can't find some time over the next couple of weeks to make some proper updates here.

**Comment by danim47c** [comment]
> Hi @danim47c. I actually started this project around the same time my first child was born, and between that and work I just haven't made my way back to this one quite yet. It stills needs a little work, but I'll do my best to get this in proper shape for others to use and/or reference. I do have a slightly more advanced example that's using typeorm as well. I'll see if I can't find some time over the next couple of weeks to make some proper updates here.

Thank you a lot, good luck with your baby 👶

**Comment by platypusrex** [comment]
@danim47c Added an example with simple authentication that showcases some more advance usage. Also added a relatively basic readme. Hopefully this is helpful. Let me know if you have any questions or ideas 💡 .
