### ISSUE TITLE
Question: GraphQL Context

### ISSUE THREAD

**Issue by tzarger** [platypusrex/next-type-graphql#6]
Hello, what is the best was to enhance the GraphQL Context with some extra properties that would come from Cookies or Authorization token depending on the calling application (web or mobile)?

**Comment by platypusrex** [comment]
Hey @tzarger. You can enhance context pretty much the same way you can with any apollo server implementation. I did add a couple of example applications to the repo, one with some basic authentication using session cookies that might be helpful here -> https://github.com/platypusrex/next-type-graphql/tree/master/examples/with-type-graphql-auth.
