### ISSUE TITLE
@Args() Supported?

### ISSUE THREAD

**Issue by tzarger** [platypusrex/next-type-graphql#7]
When using @Args() in a query or mutation, I get this build error:

Module parse failed: Unexpected character '@' (12:28)
File was processed with these loaders:
 * ./node_modules/next/dist/build/webpack/loaders/next-babel-loader.js

If I convert them to @Arg(...) it compiles.

**Comment by platypusrex** [comment]
@tzarger Not sure I can properly help you out here without some additional context and more specific examples of usage. As far as I know and have tested you should be able to use either `@Arg` or `@Args` with some limitations. There are some shortcomings with metadata reflection when transpiling TS with babel (which will be true of any Next.js application). One gotcha definitely worth noting is object destructuring when using `@Args` or `@Arg`. This just doesn't work properly. For example:

```
// this won't work
async login(@Arg('input') { email, password }: LoginInput, @Ctx() ctx: Context): Promise<User | null> {

// this will
async login(@Arg('input') input: LoginInput, @Ctx() ctx: Context): Promise<User | null> {
const { email, password } = input;
```

**Comment by tzarger** [comment]
@platypusrex Thanks for the response. That was my finding as well. It seems babel can't handle destructuring any of the decorators, including @Ctx().
